<a href="https://colab.research.google.com/github/kashishthorat812-bit/python_project_14/blob/main/Q1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
# create a 2D Array between 10 to 100
a=np.random.randint(10,101,(5,6))
print("Shape of Array :")
print(a)

# print the size of 2D Array using size
print("\nTotal number of element (Size) = ",np.size(a))

# print Data Type using dtype
print("\nData Type = ",a.dtype)

Shape of Array :
[[33 79 27 62 64 32]
 [60 79 92 50 72 55]
 [14 70 75 37 12 12]
 [39 98 81 68 59 71]
 [25 63 96 61 12 64]]

Total number of element (Size) =  30

Data Type =  int64
