<a href="https://colab.research.google.com/github/kashishthorat812-bit/python_project_14/blob/main/Q10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

marks = np.random.randint(30, 101, (10, 5))

print("Student Marks Array:\n", marks)

total_marks = np.sum(marks, axis=1)
average_marks = np.mean(marks, axis=1)

print("\nTotal Marks of each student:", total_marks)
print("Average Marks of each student:", average_marks)

highest_student = np.argmax(total_marks)
lowest_student = np.argmin(total_marks)

print("\nStudent with highest total marks: Student", highest_student + 1)
print("Highest total marks:", total_marks[highest_student])

print("Student with lowest total marks: Student", lowest_student + 1)
print("Lowest total marks:", total_marks[lowest_student])

print("\nOverall class mean:", np.mean(marks))
print("Overall class standard deviation:", np.std(marks))

top3_indices = np.argsort(total_marks)[-3:][::-1]

print("\nTop 3 students indices:", top3_indices + 1)
print("Marks of top 3 students:\n", marks[top3_indices])

Student Marks Array:
 [[74 30 36 72 83]
 [63 65 74 49 57]
 [30 70 33 40 39]
 [44 34 42 39 42]
 [95 95 33 58 32]
 [56 99 88 62 42]
 [47 81 99 82 74]
 [82 59 36 87 61]
 [71 71 78 68 89]
 [69 72 48 59 87]]

Total Marks of each student: [295 308 212 201 313 347 383 325 377 335]
Average Marks of each student: [59.  61.6 42.4 40.2 62.6 69.4 76.6 65.  75.4 67. ]

Student with highest total marks: Student 7
Highest total marks: 383
Student with lowest total marks: Student 4
Lowest total marks: 201

Overall class mean: 61.92
Overall class standard deviation: 20.444891782545586

Top 3 students indices: [7 9 6]
Marks of top 3 students:
 [[47 81 99 82 74]
 [71 71 78 68 89]
 [56 99 88 62 42]]
