<a href="https://colab.research.google.com/github/kashishthorat812-bit/python_project_14/blob/main/Q3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
# create a 4*5 matrix of random integers between 20 to 80
a=np.random.randint(20,81,(4,5))
print("Matrix :")
print(a)

# print the minimum and maximum value
print("\nMinimum Value = ",np.min(a))
print("Maximum Value = ",np.max(a))

# print the sum of all element using (sum)
print("\nSum of All Element = ",np.sum(a))

# print the mean using (mean)
print("Mean of matrix = ",np.mean(a))

# print standard deviation of matrix using (std)
print("Standard Deviation of matrix = ",np.std(a))

# print the sum of rows and column
print("\nSum of Rows = ",np.sum(a,axis=1))
print("Sum of Column = ",np.sum(a,axis=0))

Matrix :
[[39 68 69 68 44]
 [43 56 59 63 44]
 [44 56 27 21 32]
 [23 57 60 25 71]]

Minimum Value =  21
Maximum Value =  71

Sum of All Element =  969
Mean of matrix =  48.45
Standard Deviation of matrix =  16.122887458516853

Sum of Rows =  [288 265 180 236]
Sum of Column =  [149 237 215 177 191]
