<a href="https://colab.research.google.com/github/kashishthorat812-bit/python_project_14/blob/main/Q4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
# create a 1D array between 1 to 24 using arange()
a1=np.arange(1,25)
print("1D Array :")
print(a1)

# reshape the 1D array into (4,6) matrix
a2=a1.reshape(4,6)
print("\nReshape the 1D array into (4,6) matrix :")
print(a2)
print("Shape = ",np.shape(a2))

# reshape the 1D array into (3,8) matrix
b=a1.reshape(4,6)
print("\nReshape the 1D array into (3,8) matrix :")
print(b)
print("Shape = ",np.shape(b))

# reshape the 1D array into (2,3,4) 3D Array
c=a1.reshape(2,3,4)
print("\nReshape the 1D array into (2,3,4) 3D Array :")
print(c)
print("Shape = ",np.shape(c))


1D Array :
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

Reshape the 1D array into (4,6) matrix :
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape =  (4, 6)

Reshape the 1D array into (3,8) matrix :
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape =  (4, 6)

Reshape the 1D array into (2,3,4) 3D Array :
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape =  (2, 3, 4)
