<a href="https://colab.research.google.com/github/kashishthorat812-bit/python_project_14/blob/main/Q5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
arr=np.array([[10,20,30,40],
              [50,60,70,80],
              [90,100,110,120]])

print("Array :")
print(arr)

print("\nFirst Row :")
print(arr[0])

print("\nLast Column :")
print(arr[ : ,-1])

print("\nCenter 2*2 Submatrix :")
print(arr[0:2,1:3])

even_no = arr[arr%2==0]
print("\nEven Numbers :")
print(even_no)

Array :
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

First Row :
[10 20 30 40]

Last Column :
[ 40  80 120]

Center 2*2 Submatrix :
[[20 30]
 [60 70]]

Even Numbers :
[ 10  20  30  40  50  60  70  80  90 100 110 120]
