<a href="https://colab.research.google.com/github/kashishthorat812-bit/python_project_14/blob/main/Q6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
# create a 5*5 matrix of random number between
a=np.random.randint(1,101,(5,5))
print("Matrix :")
print(a)

# print the diagonal element using (diag)
print("\nDiagonal Element :")
print(np.diag(a))

# print the element greater than 50
print("\nElement greater tha 50 :")
print(a[a>50])

# print the modify matrix
a[a<30]=0
print("\nModify Matrix :")
print(a)

Matrix :
[[  9  92  60  43   8]
 [100  47  39  40  95]
 [ 13  40  88  99  12]
 [ 35   5  11  52  41]
 [ 67  41  16  63  87]]

Diagonal Element :
[ 9 47 88 52 87]

Element greater tha 50 :
[ 92  60 100  95  88  99  52  67  63  87]

Modify Matrix :
[[  0  92  60  43   0]
 [100  47  39  40  95]
 [  0  40  88  99   0]
 [ 35   0   0  52  41]
 [ 67  41   0  63  87]]
