<a href="https://colab.research.google.com/github/kashishthorat812-bit/python_project_14/blob/main/Q7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([10,20,30,40])
b=np.array([1,2,3,4])
print("Array a = ",a)
print("Array b = ",b)

# Addition of two array
c=a+b
print("\nAddition :")
print(c)

# Substraction of two array
c1=a-b
print("\nSubstraction :")
print(c1)

# Multiplication of two array
c2=a*b
print("\nMultiplication :")
print(c2)

# Division of two array
c3=a/b
print("\nDivision :")
print(c3)

# Power of  array
c4=a**b
print("\nPower :")
print(c4)

# Modul0 of two array
c5=a%b
print("\nModulo :")
print(c5)



Array a =  [10 20 30 40]
Array b =  [1 2 3 4]

Addition :
[11 22 33 44]

Substraction :
[ 9 18 27 36]

Multiplication :
[ 10  40  90 160]

Division :
[10. 10. 10. 10.]

Power :
[     10     400   27000 2560000]

Modulo :
[0 0 0 0]
