<a href="https://colab.research.google.com/github/kashishthorat812-bit/python_project_14/blob/main/Q8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
# create a 3*3 matrix
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

B = np.array([[9,8,7],
              [6,5,4],
              [3,2,1]])


print("\nMatrix A :")
print(A)
print("Matrix B :")
print(B)

# Element wise Multiplication
c=A*B
print("\nElement-wise multiplication :" )
print(c)

# Matrix multiplication using @
c1=A@B
print("\nMatrix multiplication :")
print(c1)

# element wise multiplication = it multiplies same position element of both matrix
# @ = Rows are multiplies to column


Matrix A :
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B :
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Element-wise multiplication :
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Matrix multiplication :
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
