<a href="https://colab.research.google.com/github/kashishthorat812-bit/python_project_14/blob/main/Q9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

arr = np.random.randn(6, 6)

print("Original Matrix :")
print(arr)

print("\nShape :")
print(arr.shape)

print("\nSize :")
print(arr.size)

print("\nData type :")
print(arr.dtype)

print("Index of maximum value :")
print(np.unravel_index(np.argmax(arr), arr.shape))
print("Index of minimum value :")
print(np.unravel_index(np.argmin(arr), arr.shape))

print("Top-left 3x3 submatrix:\n", arr[:3, :3])

arr[arr < 0] = np.abs(arr[arr < 0])

print("Modified Matrix:\n", arr)
print("Mean of modified matrix:", np.mean(arr))

Original Matrix :
[[ 1.09543531  1.17603642 -0.17895565 -0.55783648  2.23432762  1.74610559]
 [-0.73751656  0.13726209  1.67885924 -1.26225046 -0.85545601 -1.05981724]
 [-0.48394428  1.41644016 -0.46047802  1.369877   -0.72923975  0.96922029]
 [ 0.14549438 -0.96759751  0.50551971 -0.7186594  -0.8657221  -1.07108492]
 [ 0.44519837  0.71095302  0.51119754  0.10432687 -0.66030537  1.38803955]
 [ 0.47214675 -1.63664586  1.0641143  -0.65440075  0.16602875  0.06629271]]

Shape :
(6, 6)

Size :
36

Data type :
float64
Index of maximum value :
(np.int64(0), np.int64(4))
Index of minimum value :
(np.int64(5), np.int64(1))
Top-left 3x3 submatrix:
 [[ 1.09543531  1.17603642 -0.17895565]
 [-0.73751656  0.13726209  1.67885924]
 [-0.48394428  1.41644016 -0.46047802]]
Modified Matrix:
 [[1.09543531 1.17603642 0.17895565 0.55783648 2.23432762 1.74610559]
 [0.73751656 0.13726209 1.67885924 1.26225046 0.85545601 1.05981724]
 [0.48394428 1.41644016 0.46047802 1.369877   0.72923975 0.96922029]
 [0.1454943